---
  - name: "Deploy Metricbeat and Launch on Boot"
    hosts: webservers
    become: yes
    tasks:
    - name: "Download Metricbeat"
      command: wget https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
    - name: "Install Metricbeat"
      command: dpkg -i metricbeat-7.4.0-amd64.deb
    - name: "Configure Metricbeat"
      copy: src=/etc/ansible/files/metricbeat-cfg.yml dest=/etc/metricbeat/metricbeat.yml
    - name: "Metricbeat Modules"
      command: metricbeat modules enable docker
    - name: "Metricbeat Setup"
      command: metricbeat setup -e
    - name: "Metricbeat Service"
      service:
        name: metricbeat
        state: restarted
    - name: "Metricbeat on Boot"
      systemd:
        enabled: yes
        state: started
        name: metricbeat